name: 'Print Release Summary MarkDown/Step Summary'
description: '.NET based action for printing release summary in markdown format and set github_step_summary environment variable'
branding:
  icon: activity
  color: orange
inputs:
  release:
    description: 'Release name/ Tag Name'
    required: true
runs:
  using: 'docker' # docker if using container
  image: 'docker://kamil1993/github-release-summary-action:v1'
  # main: 'publish/DotNet.GitHubAction.dll' 
  args:
  - '-r'
  - ${{inputs.release}}